# Use this file to create a conda environment using:
# conda create -n <name> --file environment.yml

name: improver
channels:
  - conda-forge
dependencies:
  - python=3.6
  - iris=2.2
  - numpy=1.15.4
  - cftime=1.0.1
  - pandas=0.23.4
  - sphinx=1.8.1
  - python-stratify=0.1
  - pycodestyle=2.3.1
  - pylint=2.1.1
  - astroid=2.1.0
  - pytest
  - filelock
  - mock
  - pip:
    - clize
