# Use this file to create a conda environment using:
# conda create -n <name> --file environment.yml

name: improver
channels:
  - conda-forge
dependencies:
  - python=3
  - iris
  - pandas
  - sphinx
  - python-stratify
  - pytest
