name: Tests

on: [push]

jobs:
  Tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      id: cache
      with:
        path: /usr/share/miniconda/envs/improver
        key: ${{ runner.os }}-conda-improver-${{ hashFiles('**/environment.yml') }}
        restore-keys: |
          ${{ runner.OS }}-conda-improver-
    - name: Resolve and install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda env update -q --file environment.yml --name improver
        conda env list
        conda activate improver
        conda list --export
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Pytest (Unit tests)
      run:  |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver
        pytest -m "not acc"
    - name: Pylint (More linting goodness)
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver
        pylint -j 0 -E --rcfile=etc/pylintrc lib
