name: Tests

on: [push]

jobs:
  Tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      id: cache
      with:
        path: .
        key: ${{ runner.os }}-conda-fullenv-${{ hashFiles('**/environment.yml') }}
        restore-keys: |
          ${{ runner.OS }}-conda-fullenv-
    - name: Resolve and install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        $CONDA/bin/conda env update -q --file environment.yml --name base
        $CONDA/bin/pip install clize
        $CONDA/bin/conda list --export > full_environment.yml
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        $CONDA/bin/conda env update --file full_environment.yml --name base

    - name: Pytest (Unit tests)
      run:  $CONDA/bin/pytest -m "not acc"

    - name: Pycodestyle (PEP8 conventions)
      run:  $CONDA/bin/pycodestyle -v lib

    - name: Sphinx-build (Doc test)
      run: cd doc; make SPHINXBUILD=$CONDA/bin/sphinx-build html

    - name: Pylint (More linting goodness)
      run: $CONDA/bin/pylint -j 0 -E --rcfile=etc/pylintrc lib
