name: Tests

on: [push]

jobs:
  Tests:
    
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update -q --file environment.yml --name base
        $CONDA/bin/pip install clize
        $CONDA/bin/conda list --export
        
    - name: Sphinx-build (Doc test)
      run: bin/improver tests doc        
        
    - name: Pytest (Unit test)
      run: $CONDA/bin/pytest -m "not acc"

    - name: Bandit Check
      uses: jpetrucciani/bandit-check@1.6.2
      with:
        path: lib

    - name: Pycodestyle (PEP8 conventions)
      run: env PYCODESTYLE=$CONDA/bin/pycodestyle bin/improver tests pycodestyle
        
    - name: Pylint (More linting)
      run: env PYLINT=$CONDA/bin/pylint bin/improver tests pylintE
