name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
        $CONDA/bin/conda init bash
    - name: Test with pytest
      run: |
        $CONDA/bin/conda list
        $CONDA/bin/pytest
