name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
        $CONDA/bin/conda list
        $CONDA/bin/pip install clize
        
    - name: Pytest (Unit test)
      run:  $CONDA/bin/pytest -m "not acc"

    - name: Pycodestyle (PEP8 conventions)
      run:  $CONDA/bin/pycodestyle lib
        
    - name: Sphinx-build (Doc test)
      run: cd doc; make SPHINXBUILD=$CONDA/bin/sphinx-build html
        
    - name: Pylint (More linting goodness)
      run: $CONDA/bin/pylint -E --rcfile=etc/pylintrc lib
