name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
        $CONDA/bin/conda list
        $CONDA/bin/pip install clize
        
    - name: Pytest (Unit test)
      run:  $CONDA/bin/pytest -m "not acc"

    - name: Pycodestyle (PEP8 conventions)
      run: |
        FILES_TO_TEST=`find lib -type f \( -name '*.py' \
                                        -o -name 'improver-*' \
                                         ! -name 'improver-tests' \
                                         ! -name '*~' \)`
        $CONDA/bin/pycodestyle $FILES_TO_TEST
        
    - name: Sphinx-build (Doc test)
      run: |
        $CONDA/bin/sphinx-build -b html 1>/dev/null

    - name: Pylint.. (More linty goodness)
      run: |
        FILES_TO_TEST=`find lib -type f \( -name '*.py' \
                                        -o -name 'improver-*' \
                                         ! -name 'improver-tests' \
                                         ! -name '*~' \)`
        $CONDA/bin/pylint -E --rcfile=etc/pylintrc $FILES_TO_TEST
        
