name: Unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        # Create the basic testing environment
        # ------------------------------------
        # Explicitly add defaults channel, see https://github.com/conda/conda/issues/2675
        $CONDA/bin/conda init bash
        $CONDA/bin/conda config --add channels defaults
        $CONDA/bin/conda config --set always_yes yes --set changeps1 no
        $CONDA/bin/conda config --set show_channel_urls True
        $CONDA/bin/conda update --quiet conda
        $CONDA/bin/conda create --quiet -n 'test-environment' python=3.6
        $CONDA/bin/conda activate 'test-environment'

        # Download Iris 2.2 and all dependencies.
        $CONDA/bin/conda install -c conda-forge iris=2.2 cftime=1.0.1 numpy=1.15.4

        # Install our own extra dependencies (+ filelock for Iris test).
        $CONDA/bin/conda install -c conda-forge astroid=2.1.0 filelock mock netcdf4=1.4.1 numpy=1.15.4 pycodestyle=2.3.1 pylint=2.1.1 pandas=0.23.4 python-stratify=0.1 sphinx=1.8.1 coverage pytest
        pip install codacy-coverage codecov clize sigtools
        # List the name and version of all the dependencies within the conda environment.
        $CONDA/bin/conda list
    - name: Unit tests 
      run: bin/improver tests
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
